import type { ShapeToolOption } from '@blocksuite/affine-gfx-shape';
import { ShapeType } from '@blocksuite/affine-model';
import {
  DiamondIcon,
  EllipseIcon,
  RoundedRectangleIcon,
  TriangleIcon,
} from '@blocksuite/icons/lit';
import type { TemplateResult } from 'lit';

import {
  ActorIcon,
  ArrowBentLeftIcon,
  ArrowBentRightIcon,
  ArrowBentUpIcon,
  ArrowCalloutDoubleIcon,
  ArrowCalloutQuadIcon,
  ArrowCalloutUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowNotchedRightIcon,
  ArrowNotchedSignalInIcon,
  ArrowNotchedStylisedIcon,
  ArrowRightIcon,
  ArrowTwoWayHorizontalIcon,
  ArrowTwoWayVerticalIcon,
  ArrowUpIcon,
  CalloutIcon,
  CloudIcon,
  ContainerIcon,
  CubeIcon,
  CylinderIcon,
  DataStorageIcon,
  DocumentIcon,
  FlowchartAnnotation1Icon,
  FlowchartAnnotation2Icon,
  FlowchartCardIcon,
  FlowchartCollateIcon,
  FlowchartDatabaseIcon,
  FlowchartDataIcon,
  FlowchartDecisionIcon,
  FlowchartDelayIcon,
  FlowchartDirectDataIcon,
  FlowchartDisplayIcon,
  FlowchartDocumentIcon,
  FlowchartInternalStorageIcon,
  FlowchartLoopLimitIcon,
  FlowchartManualInputIcon,
  FlowchartManualOperationIcon,
  FlowchartMergeIcon,
  FlowchartMultiDocumentIcon,
  FlowchartOffPageReferenceIcon,
  FlowchartOrIcon,
  FlowchartPaperTapeIcon,
  FlowchartPredefinedProcessIcon,
  FlowchartPreparationIcon,
  FlowchartProcessIcon,
  FlowchartSequentialDataIcon,
  FlowchartSortIcon,
  FlowchartStoredDataIcon,
  FlowchartSummingFunctionIcon,
  FlowchartTerminatorIcon,
  HexagonIcon,
  HorizontalContainerIcon,
  InternalStorageIcon,
  LogicAndIcon,
  LogicOrIcon,
  MindmapBranchIcon,
  MindmapCentralIdeaIcon,
  MindmapSquareIcon,
  MindmapSubTopicIcon,
  NoteIcon,
  ParallelogramIcon,
  RectIcon,
  ScribbledDiamondIcon,
  ScribbledEllipseIcon,
  ScribbledRoundedRectangleIcon,
  ScribbledTriangleIcon,
  StepIcon,
  TapeIcon,
  TrapezoidIcon,
  TriangleRightIcon,
  VerticalContainerIcon,
} from './icons';

type Config = {
  name: ShapeToolOption['shapeName'];
  generalIcon: TemplateResult<1>;
  scribbledIcon: TemplateResult<1>;
  tooltip: string;
  disabled: boolean;
};

export const ShapeComponentConfig: Config[] = [
  {
    name: ShapeType.Rect,
    generalIcon: RectIcon,
    scribbledIcon: RectIcon,
    tooltip: 'Rectangle',
    disabled: false,
  },
  {
    name: 'roundedRect',
    generalIcon: RoundedRectangleIcon(),
    scribbledIcon: ScribbledRoundedRectangleIcon,
    tooltip: 'Rounded rectangle',
    disabled: false,
  },
  {
    name: ShapeType.Ellipse,
    generalIcon: EllipseIcon(),
    scribbledIcon: ScribbledEllipseIcon,
    tooltip: 'Ellipse',
    disabled: false,
  },
  {
    name: ShapeType.Diamond,
    generalIcon: DiamondIcon(),
    scribbledIcon: ScribbledDiamondIcon,
    tooltip: 'Diamond',
    disabled: false,
  },
];

// Shapes available in the shape browser (More menu)
export const ExtendedShapeConfig: Config[] = [
  {
    name: ShapeType.Triangle,
    generalIcon: TriangleIcon(),
    scribbledIcon: ScribbledTriangleIcon,
    tooltip: 'Triangle',
    disabled: false,
  },
  {
    name: ShapeType.TriangleRight,
    generalIcon: TriangleRightIcon,
    scribbledIcon: TriangleRightIcon,
    tooltip: 'Triangle (right)',
    disabled: false,
  },
  {
    name: ShapeType.Hexagon,
    generalIcon: HexagonIcon,
    scribbledIcon: HexagonIcon,
    tooltip: 'Hexagon',
    disabled: false,
  },
  {
    name: ShapeType.Parallelogram,
    generalIcon: ParallelogramIcon,
    scribbledIcon: ParallelogramIcon,
    tooltip: 'Parallelogram',
    disabled: false,
  },
  {
    name: ShapeType.Trapezoid,
    generalIcon: TrapezoidIcon,
    scribbledIcon: TrapezoidIcon,
    tooltip: 'Trapezoid',
    disabled: false,
  },
  {
    name: ShapeType.Step,
    generalIcon: StepIcon,
    scribbledIcon: StepIcon,
    tooltip: 'Step',
    disabled: false,
  },
  {
    name: ShapeType.Cylinder,
    generalIcon: CylinderIcon,
    scribbledIcon: CylinderIcon,
    tooltip: 'Cylinder',
    disabled: false,
  },
  {
    name: ShapeType.Cloud,
    generalIcon: CloudIcon,
    scribbledIcon: CloudIcon,
    tooltip: 'Cloud',
    disabled: false,
  },
  {
    name: ShapeType.Document,
    generalIcon: DocumentIcon,
    scribbledIcon: DocumentIcon,
    tooltip: 'Document',
    disabled: false,
  },
  {
    name: ShapeType.Note,
    generalIcon: NoteIcon,
    scribbledIcon: NoteIcon,
    tooltip: 'Note',
    disabled: false,
  },
  {
    name: ShapeType.Cube,
    generalIcon: CubeIcon,
    scribbledIcon: CubeIcon,
    tooltip: 'Cube',
    disabled: false,
  },
  {
    name: ShapeType.Callout,
    generalIcon: CalloutIcon,
    scribbledIcon: CalloutIcon,
    tooltip: 'Callout',
    disabled: false,
  },
  {
    name: ShapeType.Actor,
    generalIcon: ActorIcon,
    scribbledIcon: ActorIcon,
    tooltip: 'Actor',
    disabled: false,
  },
  {
    name: ShapeType.DataStorage,
    generalIcon: DataStorageIcon,
    scribbledIcon: DataStorageIcon,
    tooltip: 'Data storage',
    disabled: false,
  },
  {
    name: ShapeType.Tape,
    generalIcon: TapeIcon,
    scribbledIcon: TapeIcon,
    tooltip: 'Tape',
    disabled: false,
  },
  {
    name: ShapeType.InternalStorage,
    generalIcon: InternalStorageIcon,
    scribbledIcon: InternalStorageIcon,
    tooltip: 'Internal storage',
    disabled: false,
  },
  {
    name: ShapeType.LogicAnd,
    generalIcon: LogicAndIcon,
    scribbledIcon: LogicAndIcon,
    tooltip: 'AND',
    disabled: false,
  },
  {
    name: ShapeType.LogicOr,
    generalIcon: LogicOrIcon,
    scribbledIcon: LogicOrIcon,
    tooltip: 'OR',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartProcess,
    generalIcon: FlowchartProcessIcon,
    scribbledIcon: FlowchartProcessIcon,
    tooltip: 'Process',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartDecision,
    generalIcon: FlowchartDecisionIcon,
    scribbledIcon: FlowchartDecisionIcon,
    tooltip: 'Decision',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartData,
    generalIcon: FlowchartDataIcon,
    scribbledIcon: FlowchartDataIcon,
    tooltip: 'Data',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartDocument,
    generalIcon: FlowchartDocumentIcon,
    scribbledIcon: FlowchartDocumentIcon,
    tooltip: 'Document',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartManualInput,
    generalIcon: FlowchartManualInputIcon,
    scribbledIcon: FlowchartManualInputIcon,
    tooltip: 'Manual input',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartDelay,
    generalIcon: FlowchartDelayIcon,
    scribbledIcon: FlowchartDelayIcon,
    tooltip: 'Delay',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartPredefinedProcess,
    generalIcon: FlowchartPredefinedProcessIcon,
    scribbledIcon: FlowchartPredefinedProcessIcon,
    tooltip: 'Predefined process',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartStoredData,
    generalIcon: FlowchartStoredDataIcon,
    scribbledIcon: FlowchartStoredDataIcon,
    tooltip: 'Stored data',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartInternalStorage,
    generalIcon: FlowchartInternalStorageIcon,
    scribbledIcon: FlowchartInternalStorageIcon,
    tooltip: 'Internal storage',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartDatabase,
    generalIcon: FlowchartDatabaseIcon,
    scribbledIcon: FlowchartDatabaseIcon,
    tooltip: 'Database',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartSequentialData,
    generalIcon: FlowchartSequentialDataIcon,
    scribbledIcon: FlowchartSequentialDataIcon,
    tooltip: 'Sequential data',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartTerminator,
    generalIcon: FlowchartTerminatorIcon,
    scribbledIcon: FlowchartTerminatorIcon,
    tooltip: 'Terminator',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartPreparation,
    generalIcon: FlowchartPreparationIcon,
    scribbledIcon: FlowchartPreparationIcon,
    tooltip: 'Preparation',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartMerge,
    generalIcon: FlowchartMergeIcon,
    scribbledIcon: FlowchartMergeIcon,
    tooltip: 'Merge',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartPaperTape,
    generalIcon: FlowchartPaperTapeIcon,
    scribbledIcon: FlowchartPaperTapeIcon,
    tooltip: 'Paper tape',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartAnnotation1,
    generalIcon: FlowchartAnnotation1Icon,
    scribbledIcon: FlowchartAnnotation1Icon,
    tooltip: 'Annotation 1',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartAnnotation2,
    generalIcon: FlowchartAnnotation2Icon,
    scribbledIcon: FlowchartAnnotation2Icon,
    tooltip: 'Annotation 2',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartCard,
    generalIcon: FlowchartCardIcon,
    scribbledIcon: FlowchartCardIcon,
    tooltip: 'Card',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartCollate,
    generalIcon: FlowchartCollateIcon,
    scribbledIcon: FlowchartCollateIcon,
    tooltip: 'Collate',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartDirectData,
    generalIcon: FlowchartDirectDataIcon,
    scribbledIcon: FlowchartDirectDataIcon,
    tooltip: 'Direct data',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartDisplay,
    generalIcon: FlowchartDisplayIcon,
    scribbledIcon: FlowchartDisplayIcon,
    tooltip: 'Display',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartLoopLimit,
    generalIcon: FlowchartLoopLimitIcon,
    scribbledIcon: FlowchartLoopLimitIcon,
    tooltip: 'Loop limit',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartManualOperation,
    generalIcon: FlowchartManualOperationIcon,
    scribbledIcon: FlowchartManualOperationIcon,
    tooltip: 'Manual operation',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartMultiDocument,
    generalIcon: FlowchartMultiDocumentIcon,
    scribbledIcon: FlowchartMultiDocumentIcon,
    tooltip: 'Multi-document',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartOffPageReference,
    generalIcon: FlowchartOffPageReferenceIcon,
    scribbledIcon: FlowchartOffPageReferenceIcon,
    tooltip: 'Off-page reference',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartOr,
    generalIcon: FlowchartOrIcon,
    scribbledIcon: FlowchartOrIcon,
    tooltip: 'OR',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartSort,
    generalIcon: FlowchartSortIcon,
    scribbledIcon: FlowchartSortIcon,
    tooltip: 'Sort',
    disabled: false,
  },
  {
    name: ShapeType.FlowchartSummingFunction,
    generalIcon: FlowchartSummingFunctionIcon,
    scribbledIcon: FlowchartSummingFunctionIcon,
    tooltip: 'Summing function',
    disabled: false,
  },
  {
    name: ShapeType.ArrowUp,
    generalIcon: ArrowUpIcon,
    scribbledIcon: ArrowUpIcon,
    tooltip: 'Arrow up',
    disabled: false,
  },
  {
    name: ShapeType.ArrowDown,
    generalIcon: ArrowDownIcon,
    scribbledIcon: ArrowDownIcon,
    tooltip: 'Arrow down',
    disabled: false,
  },
  {
    name: ShapeType.ArrowLeft,
    generalIcon: ArrowLeftIcon,
    scribbledIcon: ArrowLeftIcon,
    tooltip: 'Arrow left',
    disabled: false,
  },
  {
    name: ShapeType.ArrowRight,
    generalIcon: ArrowRightIcon,
    scribbledIcon: ArrowRightIcon,
    tooltip: 'Arrow right',
    disabled: false,
  },
  {
    name: ShapeType.ArrowTwoWayHorizontal,
    generalIcon: ArrowTwoWayHorizontalIcon,
    scribbledIcon: ArrowTwoWayHorizontalIcon,
    tooltip: 'Two-way arrow (horizontal)',
    disabled: false,
  },
  {
    name: ShapeType.ArrowTwoWayVertical,
    generalIcon: ArrowTwoWayVerticalIcon,
    scribbledIcon: ArrowTwoWayVerticalIcon,
    tooltip: 'Two-way arrow (vertical)',
    disabled: false,
  },
  {
    name: ShapeType.ArrowBentLeft,
    generalIcon: ArrowBentLeftIcon,
    scribbledIcon: ArrowBentLeftIcon,
    tooltip: 'Bent arrow (left)',
    disabled: false,
  },
  {
    name: ShapeType.ArrowBentRight,
    generalIcon: ArrowBentRightIcon,
    scribbledIcon: ArrowBentRightIcon,
    tooltip: 'Bent arrow (right)',
    disabled: false,
  },
  {
    name: ShapeType.ArrowBentUp,
    generalIcon: ArrowBentUpIcon,
    scribbledIcon: ArrowBentUpIcon,
    tooltip: 'Bent arrow (up)',
    disabled: false,
  },
  {
    name: ShapeType.ArrowNotchedSignalIn,
    generalIcon: ArrowNotchedSignalInIcon,
    scribbledIcon: ArrowNotchedSignalInIcon,
    tooltip: 'Notched signal-in arrow',
    disabled: false,
  },
  {
    name: ShapeType.ArrowNotchedRight,
    generalIcon: ArrowNotchedRightIcon,
    scribbledIcon: ArrowNotchedRightIcon,
    tooltip: 'Right notched arrow',
    disabled: false,
  },
  {
    name: ShapeType.ArrowNotchedStylised,
    generalIcon: ArrowNotchedStylisedIcon,
    scribbledIcon: ArrowNotchedStylisedIcon,
    tooltip: 'Stylised notched arrow',
    disabled: false,
  },
  {
    name: ShapeType.ArrowCalloutUp,
    generalIcon: ArrowCalloutUpIcon,
    scribbledIcon: ArrowCalloutUpIcon,
    tooltip: 'Callout up arrow',
    disabled: false,
  },
  {
    name: ShapeType.ArrowCalloutDouble,
    generalIcon: ArrowCalloutDoubleIcon,
    scribbledIcon: ArrowCalloutDoubleIcon,
    tooltip: 'Callout double arrow',
    disabled: false,
  },
  {
    name: ShapeType.ArrowCalloutQuad,
    generalIcon: ArrowCalloutQuadIcon,
    scribbledIcon: ArrowCalloutQuadIcon,
    tooltip: 'Callout quad arrow',
    disabled: false,
  },
  {
    name: ShapeType.MindmapCentralIdea,
    generalIcon: MindmapCentralIdeaIcon,
    scribbledIcon: MindmapCentralIdeaIcon,
    tooltip: 'Mindmap central idea',
    disabled: false,
  },
  {
    name: ShapeType.MindmapBranch,
    generalIcon: MindmapBranchIcon,
    scribbledIcon: MindmapBranchIcon,
    tooltip: 'Mindmap branch',
    disabled: false,
  },
  {
    name: ShapeType.MindmapSubTopic,
    generalIcon: MindmapSubTopicIcon,
    scribbledIcon: MindmapSubTopicIcon,
    tooltip: 'Mindmap sub topic',
    disabled: false,
  },
  {
    name: ShapeType.MindmapSquare,
    generalIcon: MindmapSquareIcon,
    scribbledIcon: MindmapSquareIcon,
    tooltip: 'Mindmap square',
    disabled: false,
  },
  {
    name: ShapeType.Container,
    generalIcon: ContainerIcon,
    scribbledIcon: ContainerIcon,
    tooltip: 'Container',
    disabled: false,
  },
  {
    name: ShapeType.VerticalContainer,
    generalIcon: VerticalContainerIcon,
    scribbledIcon: VerticalContainerIcon,
    tooltip: 'Vertical container',
    disabled: false,
  },
  {
    name: ShapeType.HorizontalContainer,
    generalIcon: HorizontalContainerIcon,
    scribbledIcon: HorizontalContainerIcon,
    tooltip: 'Horizontal container',
    disabled: false,
  },
];

// All shapes combined (for shape browser)
export const AllShapeConfig: Config[] = [
  ...ShapeComponentConfig,
  ...ExtendedShapeConfig,
];

export const ShapeComponentConfigMap = ShapeComponentConfig.reduce(
  (acc, config) => {
    acc[config.name] = config;
    return acc;
  },
  {} as Record<Config['name'], Config>
);
