docs:
  - 'docs/**/*'
  - '**/README.md'
  - 'packages/templates/**/*'

tests:
  - 'tests/**/*'
  - '**/tests/**/*'
  - '**/__tests__/**/*'

mod:dev:
  - 'scripts/**/*'
  - 'packages/cli/**/*'
  - 'packages/debug/**/*'

mod:workspace: 'packages/workspace/**/*'

mod:i18n: 'packages/i18n/**/*'

mod:env: 'packages/env/**/*'

mod:hooks: 'packages/hooks/**/*'

mod:components: 'packages/components/**/*'

mod:store:
  - 'packages/jotai/**/*'
  - '**/atoms/**/*'

rust:
  - '**/*.rs'
  - '**/Cargo.toml'
  - '**/Cargo.lock'
  - '**/rust-toolchain'
  - '**/rust-toolchain.toml'
  - '**/rustfmt.toml'

package:y-indexeddb: 'packages/y-indexeddb/**/*'

app:web: 'apps/web/**/*'

app:electron: 'apps/electron/**/*'
