docs:
  - 'docs/**/*'
  - '**/README.md'
  - 'packages/templates/**/*'

test:
  - 'tests/**/*'
  - '**/tests/**/*'
  - '**/__tests__/**/*'

plugin:copilot:
  - 'plugins/copilot/**/*'

mod:dev:
  - 'scripts/**/*'
  - 'packages/cli/**/*'
  - 'packages/debug/**/*'

mod:plugin-infra:
  - 'packages/plugin-infra/**/*'

mod:workspace: 'packages/workspace/**/*'

mod:i18n: 'packages/i18n/**/*'

mod:env: 'packages/env/**/*'

mod:hooks: 'packages/hooks/**/*'

mod:component: 'packages/component/**/*'

mod:store:
  - 'packages/jotai/**/*'
  - '**/atoms/**/*'

rust:
  - '**/*.rs'
  - '**/Cargo.toml'
  - '**/Cargo.lock'
  - '**/rust-toolchain'
  - '**/rust-toolchain.toml'
  - '**/rustfmt.toml'

package:y-indexeddb: 'packages/y-indexeddb/**/*'

app:web: 'apps/web/**/*'

app:electron: 'apps/electron/**/*'

app:server: 'apps/server/**/*'
