{{- if .Values.global.database.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ quote .Values.global.database.secretName }}
type: Opaque
data:
  {{ quote .Values.global.database.secretUsernameField }}: {{ .Values.global.database.user | b64enc }}
  {{ quote .Values.global.database.secretPasswordField }}: {{ .Values.global.database.password | b64enc }}
{{- end }}
