approvedGitRepositories:
  - "https://github.com/electron/node-gyp.git"
  - "https://github.com/locize/html-parse-stringify2.git"

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-NONE}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
