compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-NONE}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmmirror.com"

yarnPath: .yarn/releases/yarn-4.9.1.cjs


httpTimeout: 600000