name: 'AFFiNE AppStream release'
description: 'Updates affine.metainfo.xml to include a new release tag'
inputs:
  version:
    description: 'New version'
    required: true
  path:
    description: 'Path to metainfo file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install XMLStarlet
      run: sudo apt-get install -y xmlstarlet
    - name: Add new release tag
      shell: bash
      run: |
        xmlstarlet edit --inplace \
          --subnode "/component/releases" --type elem -n "release" \
          --insert "/component/releases/release[last()]" --type attr -n "version" -v "${{ inputs.version }}" \
          --insert "/component/releases/release[last()]" --type attr -n "date" -v "$(date +%Y-%m-%d)" \
          --subnode "/component/releases/release[last()]" --type elem -n "url" -v "https://github.com/toeverything/AFFiNE/releases/tag/v${{ inputs.version }}" \
          "${{ inputs.path }}"
