// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null;
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = f => f.includes('libc.musl-') || f.includes('ld-musl-');

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl');
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require('child_process')
      .execSync('ldd --version', { encoding: 'utf8' })
      .includes('musl');
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./y-octo.android-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-android-arm64');
        const bindingPackageVersion =
          require('@y-octo/node-android-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./y-octo.android-arm-eabi.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-android-arm-eabi');
        const bindingPackageVersion =
          require('@y-octo/node-android-arm-eabi/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on Android ${process.arch}`)
      );
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (
        process.config?.variables?.shlib_suffix === 'dll.a' ||
        process.config?.variables?.node_target_type === 'shared_library'
      ) {
        try {
          return require('./y-octo.win32-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-win32-x64-gnu');
          const bindingPackageVersion =
            require('@y-octo/node-win32-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./y-octo.win32-x64-msvc.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-win32-x64-msvc');
          const bindingPackageVersion =
            require('@y-octo/node-win32-x64-msvc/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./y-octo.win32-ia32-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-win32-ia32-msvc');
        const bindingPackageVersion =
          require('@y-octo/node-win32-ia32-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./y-octo.win32-arm64-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-win32-arm64-msvc');
        const bindingPackageVersion =
          require('@y-octo/node-win32-arm64-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on Windows: ${process.arch}`)
      );
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./y-octo.darwin-universal.node');
    } catch (e) {
      loadErrors.push(e);
    }
    try {
      const binding = require('@y-octo/node-darwin-universal');
      const bindingPackageVersion =
        require('@y-octo/node-darwin-universal/package.json').version;
      if (
        bindingPackageVersion !== '0.25.7' &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
      ) {
        throw new Error(
          `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
        );
      }
      return binding;
    } catch (e) {
      loadErrors.push(e);
    }
    if (process.arch === 'x64') {
      try {
        return require('./y-octo.darwin-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-darwin-x64');
        const bindingPackageVersion =
          require('@y-octo/node-darwin-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./y-octo.darwin-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-darwin-arm64');
        const bindingPackageVersion =
          require('@y-octo/node-darwin-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on macOS: ${process.arch}`)
      );
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./y-octo.freebsd-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-freebsd-x64');
        const bindingPackageVersion =
          require('@y-octo/node-freebsd-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./y-octo.freebsd-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-freebsd-arm64');
        const bindingPackageVersion =
          require('@y-octo/node-freebsd-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on FreeBSD: ${process.arch}`)
      );
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./y-octo.linux-x64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-x64-musl');
          const bindingPackageVersion =
            require('@y-octo/node-linux-x64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./y-octo.linux-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-x64-gnu');
          const bindingPackageVersion =
            require('@y-octo/node-linux-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./y-octo.linux-arm64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-arm64-musl');
          const bindingPackageVersion =
            require('@y-octo/node-linux-arm64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./y-octo.linux-arm64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-arm64-gnu');
          const bindingPackageVersion =
            require('@y-octo/node-linux-arm64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./y-octo.linux-arm-musleabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-arm-musleabihf');
          const bindingPackageVersion =
            require('@y-octo/node-linux-arm-musleabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./y-octo.linux-arm-gnueabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-arm-gnueabihf');
          const bindingPackageVersion =
            require('@y-octo/node-linux-arm-gnueabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./y-octo.linux-loong64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-loong64-musl');
          const bindingPackageVersion =
            require('@y-octo/node-linux-loong64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./y-octo.linux-loong64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-loong64-gnu');
          const bindingPackageVersion =
            require('@y-octo/node-linux-loong64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./y-octo.linux-riscv64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-riscv64-musl');
          const bindingPackageVersion =
            require('@y-octo/node-linux-riscv64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./y-octo.linux-riscv64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@y-octo/node-linux-riscv64-gnu');
          const bindingPackageVersion =
            require('@y-octo/node-linux-riscv64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.25.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./y-octo.linux-ppc64-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-linux-ppc64-gnu');
        const bindingPackageVersion =
          require('@y-octo/node-linux-ppc64-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./y-octo.linux-s390x-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-linux-s390x-gnu');
        const bindingPackageVersion =
          require('@y-octo/node-linux-s390x-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on Linux: ${process.arch}`)
      );
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./y-octo.openharmony-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-openharmony-arm64');
        const bindingPackageVersion =
          require('@y-octo/node-openharmony-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./y-octo.openharmony-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-openharmony-x64');
        const bindingPackageVersion =
          require('@y-octo/node-openharmony-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./y-octo.openharmony-arm.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@y-octo/node-openharmony-arm');
        const bindingPackageVersion =
          require('@y-octo/node-openharmony-arm/package.json').version;
        if (
          bindingPackageVersion !== '0.25.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.25.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(
        new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`)
      );
    }
  } else {
    loadErrors.push(
      new Error(
        `Unsupported OS: ${process.platform}, architecture: ${process.arch}`
      )
    );
  }
}

nativeBinding = requireNative();

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null;
  let wasiBindingError = null;
  try {
    wasiBinding = require('./y-octo.wasi.cjs');
    nativeBinding = wasiBinding;
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err;
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('@y-octo/node-wasm32-wasi');
      nativeBinding = wasiBinding;
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err;
        loadErrors.push(err);
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error(
      'WASI binding not found and NAPI_RS_FORCE_WASI is set to error'
    );
    error.cause = wasiBindingError;
    throw error;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err;
          return cur;
        }),
      }
    );
  }
  throw new Error(`Failed to load native binding`);
}

module.exports = nativeBinding;
module.exports.Doc = nativeBinding.Doc;
module.exports.YArray = nativeBinding.YArray;
module.exports.YMap = nativeBinding.YMap;
module.exports.YText = nativeBinding.YText;
