ARG BASE_IMAGE=localhost:5000/toeverything/relocate:latest

FROM ${BASE_IMAGE} as relocate

# =============
# AFFiNE image
# =============
FROM caddy:2.4.6-alpine as AFFiNE
WORKDIR /app
COPY --from=relocate /app .

EXPOSE 3000
CMD ["caddy", "run"]
