/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IUserParameters =
  | {
      CreateUser: CreateUser;
    }
  | {
      User: User;
    }
  | {
      GetUserParameters: GetUserParameters;
    };

export interface CreateUser {
  avatar_url?: string | null;
  email: string;
  name: string;
  password: string;
  [k: string]: unknown;
}
export interface User {
  avatar_url?: string | null;
  created_at: number;
  email: string;
  id: string;
  name: string;
  [k: string]: unknown;
}
export interface GetUserParameters {
  email: string;
  [k: string]: unknown;
}
