export const macKeyboardShortcuts = {
  Undo: 'cmd + Z',
  Redo: 'cmd + shift + Z',
  Bold: 'cmd + B',
  Italic: 'cmd + I',
  Underline: 'cmd + U',
  Strikethrough: 'cmd + Shit + S',
  'Inline code': ' cmd + E',
  Link: 'cmd + K',
  'Body text': 'cmd + Option + 0',
  'Heading 1': 'cmd + Option + 1',
  'Heading 2': 'cmd + Option + 2',
  'Heading 3': 'cmd + Option + 3',
  'Heading 4': 'cmd + Option + 4',
  'Heading 5': 'cmd + Option + 5',
  'Heading 6': 'cmd + Option + 6',
  'Increase indent': 'Tab',
  'Reduce indent': 'Shift + Tab',
};

export const macMarkdownShortcuts = {
  Bold: '**Text**',
  Italic: '*Text*',
  Underline: '~Text~',
  Strikethrough: '~~Text~~',
  'Inline code': '`Code`',
  'Heading 1': '# + Space',
  'Heading 2': '## + Space',
  'Heading 3': '### + Space',
  'Heading 4': '#### + Space',
  'Heading 5': '##### + Space',
  'Heading 6': '###### + Space',
};

export const windowsKeyboardShortcuts = {
  Undo: 'Ctrl + Z',
  Redo: 'Ctrl + Y',
  Bold: 'Ctrl + B',
  Italic: 'Ctrl + I',
  Underline: 'Ctrl + U',
  Strikethrough: 'Ctrl + Shit + S',
  'Inline code': ' Ctrl + E',
  Link: 'Ctrl + K',
  'Body text': 'Ctrl + Shift + 0',
  'Heading 1': 'Ctrl + Shift + 1',
  'Heading 2': 'Ctrl + Shift + 2',
  'Heading 3': 'Ctrl + Shift + 3',
  'Heading 4': 'Ctrl + Shift + 4',
  'Heading 5': 'Ctrl + Shift + 5',
  'Heading 6': 'Ctrl + Shift + 6',
  'Increase indent': 'Tab',
  'Reduce indent': 'Shift + Tab',
};
export const winMarkdownShortcuts = {
  Bold: '**Text** + Space',
  Italic: '*Text* + Space',
  Underline: '~Text~ + Space',
  Strikethrough: '~~Text~~ + Space',
  'Inline code': '`Code` + Space',
  'Heading 1': '# + Space',
  'Heading 2': '## + Space',
  'Heading 3': '### + Space',
  'Heading 4': '#### + Space',
  'Heading 5': '##### + Space',
  'Heading 6': '###### + Space',
};
