export const macKeyboardShortcuts = {
  Undo: '⌘+Z',
  Redo: '⌘+⇧+Z',
  Bold: '⌘+B',
  Italic: '⌘+I',
  Underline: '⌘+U',
  Strikethrough: '⌘+⇧+S',
  'Inline code': ' ⌘+E',
  'Code block': '⌘+⌥+C',
  Link: '⌘+K',
  'Body text': '⌘+⌥+0',
  'Heading 1': '⌘+⌥+1',
  'Heading 2': '⌘+⌥+2',
  'Heading 3': '⌘+⌥+3',
  'Heading 4': '⌘+⌥+4',
  'Heading 5': '⌘+⌥+5',
  'Heading 6': '⌘+⌥+6',
  'Increase indent': 'Tab',
  'Reduce indent': '⇧+Tab',
};

export const macMarkdownShortcuts = {
  Bold: '**Text** ',
  Italic: '*Text* ',
  Underline: '~Text~ ',
  Strikethrough: '~~Text~~ ',
  Divider: '***',
  'Inline code': '`Text` ',
  'Code block': '``` Space',
  'Heading 1': '# Text',
  'Heading 2': '## Text',
  'Heading 3': '### Text',
  'Heading 4': '#### Text',
  'Heading 5': '##### Text',
  'Heading 6': '###### Text',
};

export const windowsKeyboardShortcuts = {
  Undo: 'Ctrl+Z',
  Redo: 'Ctrl+Y',
  Bold: 'Ctrl+B',
  Italic: 'Ctrl+I',
  Underline: 'Ctrl+U',
  Strikethrough: 'Ctrl+Shift+S',
  'Inline code': ' Ctrl+E',
  'Code block': 'Ctrl+Alt+C',
  Link: 'Ctrl+K',
  'Body text': 'Ctrl+Shift+0',
  'Heading 1': 'Ctrl+Shift+1',
  'Heading 2': 'Ctrl+Shift+2',
  'Heading 3': 'Ctrl+Shift+3',
  'Heading 4': 'Ctrl+Shift+4',
  'Heading 5': 'Ctrl+Shift+5',
  'Heading 6': 'Ctrl+Shift+6',
  'Increase indent': 'Tab',
  'Reduce indent': 'Shift+Tab',
};
export const winMarkdownShortcuts = {
  Bold: '**Text** ',
  Italic: '*Text* ',
  Underline: '~Text~ ',
  Strikethrough: '~~Text~~ ',
  'Inline code': '`Text` ',
  'Code block': '``` Text',
  'Heading 1': '# Text',
  'Heading 2': '## Text',
  'Heading 3': '### Text',
  'Heading 4': '#### Text',
  'Heading 5': '##### Text',
  'Heading 6': '###### Text',
};
