import type { AppConfig } from '../../src/config/env.js';

export function testConfig(overrides: Partial<AppConfig> = {}): AppConfig {
  return {
    NODE_ENV: 'test',
    HOST: '127.0.0.1',
    PORT: 3010,
    LOG_LEVEL: 'silent',
    MOSAIC_PUBLIC_URL: 'http://localhost:3010',
    MOSAIC_SERVER_NAME: 'Mosaic',
    MOSAIC_SERVER_VERSION: '0.1.0',
    MOSAIC_COMPAT_VERSION: '0.27.5',
    MOSAIC_FEATURES: [],
    MOSAIC_SERVER: undefined,
    MOSAIC_STATIC_DIR: undefined,
    DATABASE_URL: undefined,
    REDIS_URL: undefined,
    MOSAIC_PERSISTENCE: 'memory',
    MOSAIC_ALLOW_SIGNUP: true,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
    SESSION_IDLE_MS: 7 * 24 * 60 * 60 * 1000,
    SESSION_ABSOLUTE_MS: 30 * 24 * 60 * 60 * 1000,
    ACCESS_TOKEN_MS: 15 * 60 * 1000,
    REFRESH_TOKEN_MS: 30 * 24 * 60 * 60 * 1000,
    COOKIE_SECURE: false,
    RATE_LIMIT_MAX: 10_000,
    RATE_LIMIT_AUTH_MAX: 10_000,
    SYNC_COMPACT_UPDATES: 64,
    SYNC_MAX_UPDATE_BYTES: 1_048_576,
    BLOB_DRIVER: 'memory',
    BLOB_DIR: 'data/blobs',
    BLOB_MAX_BYTES: 100 * 1024 * 1024,
    BLOB_STORAGE_QUOTA_BYTES: 100 * 1024 * 1024 * 1024,
    BLOB_MULTIPART_THRESHOLD: 8 * 1024 * 1024,
    BLOB_PART_SIZE: 5 * 1024 * 1024,
    BLOB_UPLOAD_TTL_MS: 60 * 60 * 1000,
    DOC_HISTORY_LIMIT: 50,
    OTEL_EXPORTER_OTLP_ENDPOINT: undefined,
    OTEL_SERVICE_NAME: 'mosaic-server-test',
    MOSAIC_OIDC_ISSUER: undefined,
    MOSAIC_OIDC_CLIENT_ID: undefined,
    MOSAIC_OIDC_CLIENT_SECRET: undefined,
    MOSAIC_OIDC_PROVIDER: undefined,
    MOSAIC_SAML_IDP_SSO_URL: undefined,
    MOSAIC_SAML_IDP_ENTITY_ID: undefined,
    MOSAIC_SAML_CERTIFICATE: undefined,
    MOSAIC_AI_BASE_URL: 'https://api.openai.com/v1',
    MOSAIC_AI_API_KEY: undefined,
    MOSAIC_AI_MODEL: 'gpt-4o-mini',
    MOSAIC_SIEM_WEBHOOK_URL: undefined,
    MOSAIC_JIRA_BASE_URL: undefined,
    MOSAIC_JIRA_EMAIL: undefined,
    MOSAIC_JIRA_API_TOKEN: undefined,
    MOSAIC_JIRA_WEBHOOK_SECRET: undefined,
    AUDIT_RETENTION_DAYS: 365,
    flavor: 'allinone',
    deploymentType: 'selfhosted',
    allowSignup: true,
    cookieSecure: false,
    ...overrides,
  };
}
