/*
  Warnings:

  - A unique constraint covering the columns `[sid]` on the table `workspaces` will be added. If there are existing duplicate values, this will fail.

*/
-- AlterTable
ALTER TABLE "workspaces" ADD COLUMN "sid" INT GENERATED BY DEFAULT AS IDENTITY;

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_sid_key" ON "workspaces"("sid");

-- AlterTable
ALTER TABLE "workspaces" ADD COLUMN     "indexed" BOOLEAN NOT NULL DEFAULT false;
