/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Storage {
  constructor(path: string);
  error(): string | null;
  getBlob(workspaceId: string | undefined | null, id: string): Promise<Buffer>;
  connect(workspaceId: string, remote: string): Workspace | null;
  sync(workspaceId: string, remote: string): Workspace;
}
export class Workspace {
  constructor(id: string);
  id(): string;
  clientId(): number;
  search(query: string): string;
  getSearchIndex(): Array<string>;
  setSearchIndex(fields: Array<string>): boolean;
}
