export const TemplateData = [
    {
        name: 'Design',
        subList: [
            { name: '🚘 Roadmap' },
            { name: '🔬 User Research Database' },
            { name: '🎒 Design Tasks' },
            { name: '✏️ Meeting Notes' },
            { name: '🖋️ Design System' },
            { name: '🎯 Company goals' },
        ],
    },
    {
        name: 'Student',
        subList: [
            { name: '✏️ Class Notes' },
            { name: '🏗 Job Applications' },
            { name: '⚖️ Grade Calculator' },
            { name: '🏡 Club Homepage' },
            { name: '📚 Reading List' },
            { name: '📜 Thesis Planning' },
            { name: '📍 Cornell Notes System' },
            { name: '📇 Personal CRM' },
            { name: '✌️ Roommate Space' },
            { name: '💸 Simple Budget' },
            { name: '📄 Syllabus' },
            { name: '🏠 Classroom Home' },
            { name: '📋 Lesson Plans' },
            { name: '🗓 Course Schedule' },
            { name: '👋 Class Directory' },
        ],
    },
    {
        name: 'Engineering',
        subList: [
            { name: '🎒 To-Do' },
            { name: '🚘 Roadmap' },
            { name: '📓 Engineering Wiki' },
            { name: '📎 Docs' },
            { name: '✏️ Meeting Notes' },
            { name: '🎯 Company goals' },
        ],
    },
    {
        name: 'Human resources',
        subList: [
            { name: '💼 Job Board' },
            { name: '✏️ Meeting Notes' },
            { name: '🚂 New Hire Onboarding' },
            { name: '📮 Applicant Tracker' },
            { name: '🏠 Company Home' },
        ],
    },
    {
        name: 'Marketing',
        subList: [
            { name: '🎨 Brand Assets' },
            { name: '✏️ Meeting Notes' },
            { name: '🎤 Media List' },
            { name: '📆 Content Calendar' },
            { name: '🎟️ Mood Board' },
        ],
    },
    {
        name: 'Personal',
        subList: [
            { name: '📌 Quick Note' },
            { name: '🏠 Personal Home' },
            { name: '✔️ Task List' },
            { name: '🖊️ Journal' },
            { name: '📚 Reading List' },
            { name: '🏔️ Goals' },
            { name: '✈️ Travel Planner' },
            { name: '✏️ Blog Post' },
            { name: '📔 Simple Notebook' },
            { name: '👟 Habit Tracker' },
            { name: '🧭 Life Wiki' },
            { name: '👔 Resume' },
            { name: '📥 Job Applications' },
            { name: '📕 Weekly Agenda' },
        ],
    },
    {
        name: 'Other',
        subList: [
            { name: '️📝 Meeting Notes' },
            { name: '📄 Docs' },
            { name: '🏠 Team Home' },
            { name: '☑️ Team Tasks' },
            { name: '✔️ Task List' },
        ],
    },
    {
        name: 'Product management',
        subList: [
            { name: '🚘 Roadmap' },
            { name: ' User Research Database' },
            { name: '📎 Docs' },
            { name: '✏️ Meeting Notes' },
            { name: '🏗 Product Wiki' },
            { name: '🎯 Company goals' },
        ],
    },
    {
        name: 'Sales',
        subList: [
            { name: '✏️ Meeting Notes' },
            { name: '👟 Sales CRM' },
            { name: '📕 Sales Wiki' },
            { name: '🎯 Competitive Analysis' },
            { name: '✌️ Sales Assets' },
        ],
    },
    {
        name: 'Support',
        subList: [
            { name: '✌️ Team Directory' },
            { name: '❓ Product FAQs' },
            { name: '✏️ Meeting Notes' },
            { name: '🎒 Task List' },
            { name: '🚨 Help Center' },
            { name: '📎 Process Docs' },
        ],
    },
];
