import { ShapeType } from '@blocksuite/affine-model';

export const DRAWIO_STENCIL_SHAPE_MAP: Partial<Record<ShapeType, string>> = {
  [ShapeType.Cylinder]: 'Database',
  [ShapeType.Document]: 'Document',
  [ShapeType.DataStorage]: 'Stored Data',
  [ShapeType.InternalStorage]: 'Internal Storage',
  [ShapeType.Tape]: 'Paper Tape',
  [ShapeType.LogicAnd]: 'AND',
  [ShapeType.LogicOr]: 'OR',
  [ShapeType.Callout]: 'Rectangular Callout',
  [ShapeType.Step]: 'Step',
  [ShapeType.FlowchartProcess]: 'Predefined Process',
  [ShapeType.FlowchartDecision]: 'Decision',
  [ShapeType.FlowchartData]: 'Data',
  [ShapeType.FlowchartManualInput]: 'Manual Input',
  [ShapeType.FlowchartDelay]: 'Delay',
  [ShapeType.FlowchartPredefinedProcess]: 'Predefined Process',
  [ShapeType.FlowchartDocument]: 'Document',
  [ShapeType.FlowchartStoredData]: 'Stored Data',
  [ShapeType.FlowchartInternalStorage]: 'Internal Storage',
  [ShapeType.FlowchartDatabase]: 'Database',
  [ShapeType.FlowchartSequentialData]: 'Sequential Data',
  [ShapeType.FlowchartTerminator]: 'Terminator',
  [ShapeType.FlowchartPreparation]: 'Preparation',
  [ShapeType.FlowchartMerge]: 'Merge or Storage',
  [ShapeType.FlowchartPaperTape]: 'Paper Tape',
  [ShapeType.FlowchartAnnotation1]: 'Annotation 1',
  [ShapeType.FlowchartAnnotation2]: 'Annotation 2',
  [ShapeType.FlowchartCard]: 'Card',
  [ShapeType.FlowchartCollate]: 'Collate',
  [ShapeType.FlowchartDirectData]: 'Direct Data',
  [ShapeType.FlowchartDisplay]: 'Display',
  [ShapeType.FlowchartLoopLimit]: 'Loop Limit',
  [ShapeType.FlowchartManualOperation]: 'Manual Operation',
  [ShapeType.FlowchartMultiDocument]: 'Multi-Document',
  [ShapeType.FlowchartOffPageReference]: 'Off-page Reference',
  [ShapeType.FlowchartOr]: 'Or',
  [ShapeType.FlowchartSort]: 'Sort',
  [ShapeType.FlowchartSummingFunction]: 'Summing Function',
  [ShapeType.ArrowUp]: 'Arrow Up',
  [ShapeType.ArrowDown]: 'Arrow Down',
  [ShapeType.ArrowLeft]: 'Arrow Left',
  [ShapeType.ArrowRight]: 'Arrow Right',
  [ShapeType.ArrowTwoWayHorizontal]: 'Two Way Arrow Horizontal',
  [ShapeType.ArrowTwoWayVertical]: 'Two Way Arrow Vertical',
  [ShapeType.ArrowBentLeft]: 'Bent Left Arrow',
  [ShapeType.ArrowBentRight]: 'Bent Right Arrow',
  [ShapeType.ArrowBentUp]: 'Bent Up Arrow',
  [ShapeType.ArrowNotchedSignalIn]: 'Notched Signal-in Arrow',
  [ShapeType.ArrowNotchedRight]: 'Right Notched Arrow',
  [ShapeType.ArrowNotchedStylised]: 'Stylised Notched Arrow',
  [ShapeType.ArrowCalloutUp]: 'Callout Up Arrow',
  [ShapeType.ArrowCalloutDouble]: 'Callout Double Arrow',
  [ShapeType.ArrowCalloutQuad]: 'Callout Quad Arrow',
};
