import { ShapeType } from '@blocksuite/affine-model';

export const DRAWIO_STENCIL_SHAPE_MAP: Partial<Record<ShapeType, string>> = {
  [ShapeType.Cylinder]: 'Database',
  [ShapeType.Document]: 'Document',
  [ShapeType.DataStorage]: 'Stored Data',
  [ShapeType.InternalStorage]: 'Internal Storage',
  [ShapeType.Tape]: 'Paper Tape',
  [ShapeType.LogicAnd]: 'AND',
  [ShapeType.LogicOr]: 'OR',
  [ShapeType.Callout]: 'Rectangular Callout',
  [ShapeType.Step]: 'Step',
  [ShapeType.FlowchartProcess]: 'Predefined Process',
  [ShapeType.FlowchartDecision]: 'Decision',
  [ShapeType.FlowchartData]: 'Data',
  [ShapeType.FlowchartManualInput]: 'Manual Input',
  [ShapeType.FlowchartDelay]: 'Delay',
  [ShapeType.FlowchartPredefinedProcess]: 'Predefined Process',
  [ShapeType.FlowchartDocument]: 'Document',
  [ShapeType.FlowchartStoredData]: 'Stored Data',
  [ShapeType.FlowchartInternalStorage]: 'Internal Storage',
  [ShapeType.FlowchartDatabase]: 'Database',
  [ShapeType.FlowchartSequentialData]: 'Sequential Data',
  [ShapeType.FlowchartTerminator]: 'Terminator',
  [ShapeType.FlowchartPreparation]: 'Preparation',
  [ShapeType.FlowchartMerge]: 'Merge or Storage',
  [ShapeType.FlowchartPaperTape]: 'Paper Tape',
  [ShapeType.ArrowUp]: 'Arrow Up',
  [ShapeType.ArrowDown]: 'Arrow Down',
  [ShapeType.ArrowLeft]: 'Arrow Left',
  [ShapeType.ArrowRight]: 'Arrow Right',
  [ShapeType.ArrowTwoWayHorizontal]: 'Two Way Arrow Horizontal',
  [ShapeType.ArrowTwoWayVertical]: 'Two Way Arrow Vertical',
};
