global:
  app:
    buildType: 'stable'
  ingress:
    enabled: false
    className: ''
    # hosts for ingress rules
    # e.g.
    # hosts:
    #  - affine.pro
    #  - www.affine.pro
    hosts:
      - affine.pro
    tls: []
  secret:
    secretName: 'server-private-key'
    privateKey: ''
  database:
    user: 'postgres'
    host: 'pg-postgresql'
    port: '5432'
    name: 'affine'
    password: ''
  redis:
    host: 'redis-master'
    port: '6379'
    username: ''
    password: ''
    database: 0
  indexer:
    enabled: false
    provider: embedded
    endpoint: ''
    apiKey: ''
    username: ''
    password: ''
  deployment:
    # change to 'selfhosted' and 'unknown' if this chart is ready to be used for selfhosted deployment
    type: 'affine'
    platform: 'gcp'

graphql:
  service:
    type: ClusterIP
    port: 3000
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

front:
  services:
    sync:
      name: affine-sync
      type: ClusterIP
      port: 3010
      backendConfig:
        name: affine-sync-backendconfig
        timeoutSec: 10800
      annotations: {}
    renderer:
      name: affine-renderer
      type: ClusterIP
      port: 3000
      annotations:
        cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'
    web:
      name: affine-web
      type: ClusterIP
      port: 8080

worker:
  replicaCount: 1
  image:
    repository: ghcr.io/toeverything/affine
    tag: ''
  env: 'production'
  nodeOptions: '--max-old-space-size=3072'
  app:
    port: 3002
    host: '0.0.0.0'
    https: true
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 2000
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  serviceAccount:
    create: true
    annotations: {}
    name: 'affine-worker'
  resources:
    limits:
      cpu: '1'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 2Gi
  probe:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
    liveness:
      initialDelaySeconds: 60
      failureThreshold: 12
    readiness: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
