{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "affine.fullname" . }}-migration
  labels:
    {{- include "affine.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "affine.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "node ./scripts/self-host-predeploy.js"]
          {{- include "affine.env" . | nindent 10 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if include "affine.hasMigrationVolumes" . }}
          volumeMounts:
            {{- include "affine.migrationVolumeMounts" . | nindent 12 }}
          {{- end }}
      {{- if include "affine.hasMigrationVolumes" . }}
      volumes:
        {{- include "affine.migrationVolumes" . | nindent 8 }}
      {{- end }}
{{- end }}
