#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# check lockfile is up to date
yarn install --mode=update-lockfile

# build infra code
yarn -T run build:infra

# lint staged files
yarn exec lint-staged

# type check
yarn typecheck

# circular dependency check
yarn circular
