#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# check lockfile is up to date
yarn install --mode=skip-build --inline-builds --immutable

# build infra code
yarn -T run build:infra

# generate prisma client type
yarn workspace @affine/server prisma generate

# generate i18n
yarn i18n-codegen gen

# lint staged files
yarn exec lint-staged

# type check
yarn typecheck

# circular dependency check
yarn circular
