/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IBlobParameters =
  | {
      Put: PutBlob;
    }
  | {
      Get: GetBlob;
    };

export interface PutBlob {
  [k: string]: unknown;
  blob: number[];
  workspace_id: number;
}
export interface GetBlob {
  [k: string]: unknown;
  id: string;
  workspace_id: number;
}
