name: Lint

on:
    push:
        branches: [master]
    # pull_request:
    #     branches: [master]

# Cancels all previous workflow runs for pull requests that have not completed.
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # The concurrency group contains the workflow name and the branch name for
    # pull requests or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    main:
        strategy:
            matrix:
                node-version: [16]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        # TODO Remove the next line after cleaning all errors
        continue-on-error: true

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              # https://github.com/actions/setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install node modules
              run: pnpm install

            - name: Lint
              if: always()
              run: pnpm run lint:with-cache

            # - name: Check
            #   if: always()
            #   run: pnpm run check

            # - name: Format Check
            #   if: always()
            #   run: pnpm run format:ci

            # - name: Build
            #  run: pnpm run build

            # - name: Test
            #   run: pnpm run test
