name: Release Desktop/Mobile Automatically

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+'
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  dispatch-release-desktop:
    runs-on: ubuntu-latest
    name: Setup Release Desktop
    steps:
      - name: dispatch desktop release by tag
        if: ${{ github.event_name == 'push' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release-desktop.yml
          inputs: '{ "build-type": "canary", "is-draft": false, "is-pre-release": true }'

      - name: dispatch desktop release by schedule
        if: ${{ github.event_name == 'schedule' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release-desktop.yml
          inputs: '{ "build-type": "canary", "is-draft": false, "is-pre-release": true }'
          ref: canary
      - name: dispatch desktop release by tag
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release-mobile.yml
          inputs: '{ "build-type": "canary", "build-target": "distribution" }'
